# Generated by Django 5.2.14 on 2026-05-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('supertype', models.CharField(default='Pokemon', max_length=50)),
                ('subtypes', models.JSONField(blank=True, default=list)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('rarity', models.CharField(blank=True, choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Rare Holo', 'Rare Holo'), ('Rare Holo EX', 'Rare Holo EX'), ('Rare Holo GX', 'Rare Holo GX'), ('Rare Holo V', 'Rare Holo V'), ('Rare Holo VMAX', 'Rare Holo VMAX'), ('Rare Ultra', 'Rare Ultra'), ('Rare Secret', 'Rare Secret'), ('Amazing Rare', 'Amazing Rare'), ('Rare Rainbow', 'Rare Rainbow'), ('Promo', 'Promo')], db_index=True, max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('flavor_text', models.TextField(blank=True)),
                ('image_small', models.URLField(blank=True)),
                ('image_large', models.URLField(blank=True)),
                ('evolves_from', models.CharField(blank=True, max_length=200)),
                ('retreat_cost', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cardset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('series', models.CharField(blank=True, max_length=200)),
                ('printed_total', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('symbol_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Set',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('converted_cost', models.IntegerField(default=0)),
                ('cost', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='cards.card')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.cardset'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcg_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tcg_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tcg_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tcg_market', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cm_avg1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cm_avg7', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cm_avg30', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistances', to='cards.card')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.type')),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.type')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('card', 'type')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='cards', through='cards.CardType', to='cards.type'),
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='cards.card')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.type')),
            ],
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['name', 'rarity'], name='cards_card_name_56d24c_idx'),
        ),
    ]
