# Generated by Django 5.2.14 on 2026-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='damage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
