# Generated by Django 5.2.14 on 2026-05-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_attack_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='cards.card'),
        ),
    ]
